language: node_js
node_js: node
cache:
  directories:
    - node_modules
before_install:
- npm install -g hexo-cli
install: npm install
script:
- git clone https://github.com/sakitam-fdd/hexo-theme-next.git themes/next
- hexo clean
- hexo generate
- export HEXO_ALGOLIA_INDEXING_KEY={HEXO_ALGOLIA_KEY}
- set HEXO_ALGOLIA_INDEXING_KEY={HEXO_ALGOLIA_KEY}
- hexo algolia
after_script:
- cd ./dist
- git init
- git config --global user.name 'sakitam-fdd'
- git config --global user.email 'smilefdd@gmail.com'
- git add .
- git commit -m "update my website"
- git push --force --quiet "https://${TRAVIS_GITHUB}@github.com/sakitam-fdd/sakitam-fdd.github.io" master:master
