language: node_js
node_js: node
cache:
  directories:
    - node_modules
before_install:
#- npm config set registry https://registry.npm.taobao.org
#- npm config get registry
- npm install -g hexo-cli
#- npm install -g hexo
install: npm install
script:
- hexo clean
- hexo generate
after_script:
- git config --global user.name 'FDD'
- git config --global user.email 'smileFDD@gmail.com'
- sed -i'' "s~git@github.com/sakitam-fdd/sakitam-fdd.github.io.git~https://${github}:x-oauth-basic@github.com/sakitam-fdd/sakitam-fdd.github.io.git~" _config.yml
after_success:
- hexo deploy